<?php
  require('../../includes/process/db_conn.php');
  require('../../includes/process/func.php');
  require('../../includes/fpdf/fpdf.php');

  if(isset($_GET['id'])){
    $id = $_GET['id'];

    $sql = "SELECT `child`, `father`, `mother`, `bplace`, DAY(`bday`) AS `bdate`, MONTH(`bday`) AS `bmonth`, YEAR(`bday`) AS `byear`,  `church`, MONTH(`baptDate`) AS baptMonth, DAY(`baptDate`) AS baptDay, YEAR(`baptDate`) AS baptYear, `priest`, `sponsor1`, `sponsor2`, `regNum`, `pageNum`, `num`, `issued`, `purpose`, `vicar` FROM `baptismal` WHERE `id` LIKE '$id'";
    $query = mysqli_query($conn, $sql);

   

    while($row = mysqli_fetch_array($query)){
      $birthMonth = getMonthName($row['bmonth']);
      $baptMonth = getMonthName($row['baptMonth']);
      $pdf = new FPDF();
      $pdf->AddPage('P', 'A4');
      $pdf->SetFont('Arial', 'B', 18);
      $pdf->SetTextColor(255, 0, 0);
      $pdf->Cell(195, 15, "Certificate of Baptism", 0, 0, 'C');
      $pdf->Ln(7);
      $pdf->SetFont('Arial', 'B', 12);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(195,15, "Diocese of Legazpi", 0, 0, 'C');
      $pdf->Ln(25);
      $pdf->SetFont('Arial', '', 12);
      $pdf->Cell(195, 15, "PARISH OF", 0, 0, 'C');
      $pdf->Ln(6);
      $pdf->Cell(195, 15, "STS. PETER & PAUL PARISH", 0, 0, 'C');
      $pdf->Ln(6);
      $pdf->Cell(195, 15, "Polangui, Albay", 0, 0, 'C');
      $pdf->Ln(25);
      $pdf->SetFont('Arial', 'B', 14);
      $pdf->SetTextColor(255, 0, 0);
      $pdf->Cell(195, 15, "This is to Certify", 0, 0, 'C');
      $pdf->Ln(20);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         That");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(140, 5, $row['child'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         Child of");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(140, 5, $row['father'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         and");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(140, 5, $row['mother'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         Born in");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(140, 5, $row['bplace'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         On the");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(25, 5, $row['bdate'], 'B', 0, 'C');
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(25, 5, "     day of");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(60, 5, $birthMonth, 'B', 0, 'C');
      $pdf->Cell(10, 5, ',');
      $pdf->Cell(20, 5, $row['byear'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(70, 5, "         Has received in the Church of");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(95, 5, "STS. PETER & PAUL PARISH", 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         On the");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(25, 5, $row['baptDay'], 'B', 0, 'C');
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(25, 5, "     day of");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(60, 5, $baptMonth, 'B', 0, 'C');
      $pdf->Cell(10, 5, ',');
      $pdf->Cell(20, 5, $row['baptYear'], 'B', 0, 'C');
      $pdf->Ln(15);
      $pdf->SetFont('Arial', 'B', 14);
      $pdf->SetTextColor(255, 0, 0);
      $pdf->Cell(195, 15, 'The Holy Sacrament of Baptism', 0, 0, 'C');
      $pdf->Ln(15);
      $pdf->SetFont('Arial', '', 11);
      $pdf->SetTextColor(0, 0, 0);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         By the Rev");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(130, 5, $row['priest'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(40, 5, "         The sponsor being");
      $pdf->Cell(5, 5, '');
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(120, 5, $row['sponsor1'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(25, 5, "         and");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(140, 5, $row['sponsor2'], 'B', 0, 'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(90, 5, '         As appears from the Baptismal Register No.');
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(75, 5, $row['regNum'], 'B', 0, 
      'C');
      $pdf->Ln(8);
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(20, 5, "         Page");
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(20, 5, $row['pageNum'], 'B', 0, 'C');
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(2, 5, ",");
      $pdf->Cell(7, 5, 'No');
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(20, 5, $row['num'], 'B', 0, 'C');
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(40, 5, 'of this church.');
      $pdf->Ln(15);
      $pdf->Cell(10, 5, '');
      $pdf->Cell(33, 5, '         Date issued:');
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(45, 5, $row['issued'], 'B', 0, 'C');
      $pdf->Cell(22, 5, '');
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(20, 5, 'Purpose:');
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(45, 5, $row['purpose'], 'B', 0, 'C');
      $pdf->Ln(30);
      $pdf->SetFont('Arial', 'I', 11);
      $pdf->Cell(20, 5, '');
      $pdf->Cell(80, 5, $row['vicar'], 'B', 0, 'C');
      $pdf->Ln(5);
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(20, 5, '');
      $pdf->Cell(80, 5, 'Parish Priest/Parochial Vicar', 0, 0, 'C');
      $pdf->Output('I', $row['child'].' - Certificate of Baptism');
    }
  }
?>