<?php
  require('../../includes/fpdf/fpdf.php');

  $pdf = new FPDF();
  $pdf->AddPage('P', 'Legal');
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(195, 20, "OFFICE OF THE CIVIL REGISTRAR GENERAL", 0, 0, 'C');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', 'b', 16);
  $pdf->Cell(195, 20, "CERTIFICATE OF MARRIAGE", 0, 0, 'C');
  $pdf->Ln(20);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(15, 3, "Province");
  $pdf->SetFont('Arial', 'b', 11);
  $pdf->Cell(100, 3, 'Albay', 'B', 0, 'C');
  $pdf->Cell(10, 15, '');
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(30, 15, 'Registry No.');
  $pdf->SetFont('Arial', 'b', 11);
  $pdf->Cell(40, 15, '9090', 0, 0, 'C');
  $pdf->Ln(6);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(25, 5, 'City/Municipality');
  $pdf->SetFont('Arial', 'b', 11);
  $pdf->Cell(90, 5, 'Polangui', 'B', 0, 'C');
  $pdf->Ln(25);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(30, 22, '');
  $pdf->SetFont('Arial', 'b', 10);
  $pdf->Cell(80, 5, 'HUSBAND', 0, 0, 'C');
  $pdf->Cell(80, 5, 'WIFE', 0, 0, 'C');
  $pdf->Ln(7);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(30, 2, "1. Name of");
  $pdf->Cell(5, 2, '(First)');
  $pdf->Cell(10, 2, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(58, 2, 'First Name', 'B', 0, 'C');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(70, 2, 'First Name', 'B', 0, 'C');
  $pdf->Ln(5);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(30, 2, "    Contracting");
  $pdf->Cell(5, 2, '(Middle)');
  $pdf->Cell(10, 2, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(58, 2, 'Middle Name', 'B', 0, 'C');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(70, 2, 'Middle Name', 'B', 0, 'C');
  $pdf->Ln(5);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(30, 2, "    Parties");
  $pdf->Cell(5, 2, '(Last)');
  $pdf->Cell(10, 2, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(58, 2, 'Last Name', 'B', 0, 'C');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(70, 2, 'Last Name', 'B', 0, 'C');
  $pdf->Ln(7);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(30, 2, '2a. Date of Birth');
  $pdf->Cell(3, 2, '');
  $pdf->Cell(5, 2, '(Day)');
  $pdf->Cell(14, 2, '');
  $pdf->Cell(5, 2, '(Month)');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(5, 2, '(Year)');
  $pdf->Cell(15, 2, '');
  $pdf->Cell(5, 2, '(Age)');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(5, 2, '(Day)');
  $pdf->Cell(14, 2, '');
  $pdf->Cell(5, 2, '(Month)');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(5, 2, '(Year)');
  $pdf->Cell(15, 2, '');
  $pdf->Cell(5, 2, '(Age)');
  $pdf->Ln(5);
  $pdf->Cell(30, 2, '2b. Age');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(3, 2, '');
  $pdf->Cell(5, 2, '07');
  $pdf->Cell(14, 2, '');
  $pdf->Cell(5, 2, 'September');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(5, 2, '1987');
  $pdf->Cell(15, 2, '');
  $pdf->Cell(5, 2, '30');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(5, 2, '07');
  $pdf->Cell(14, 2, '');
  $pdf->Cell(5, 2, 'September');
  $pdf->Cell(18, 2, '');
  $pdf->Cell(5, 2, '1987');
  $pdf->Cell(15, 2, '');
  $pdf->Cell(5, 2, '30');
  $pdf->Ln(7);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '3. Place of Birth');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(City/Municipality)');
  $pdf->Cell(30, 2, '');
  $pdf->Cell(5, 2, '(Province)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Country)');
  $pdf->Cell(23, 2, '');
  $pdf->Cell(5, 2, '(City/Municipality)');
  $pdf->Cell(30, 2, '');
  $pdf->Cell(5, 2, '(Province)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Country)');
  $pdf->Ln(5);
  $pdf->Cell(5, 2, '');
  $pdf->SetFont('Arial' , 'b', 9);
  $pdf->Cell(25, 2, '');
  $pdf->Cell(7, 2, 'Polangui');
  $pdf->Cell(27, 2, '');
  $pdf->Cell(7, 2, 'Albay');
  $pdf->Cell(15, 2, '');
  $pdf->Cell(5, 2, 'Philippines');
  $pdf->Cell(27, 2, '');
  $pdf->Cell(7, 2, 'Polangui');
  $pdf->Cell(27, 2, '');
  $pdf->Cell(7, 2, 'Albay');
  $pdf->Cell(15, 2, '');
  $pdf->Cell(5, 2, 'Philippines');
  $pdf->Ln(7);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '4a. Sex');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(7, 2, '(Sex)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(10, 2, '(Citizenship)');
  $pdf->Cell(51.5, 2, '');
  $pdf->Cell(7, 2, '(Sex)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(10, 2, '(Citizenship)');
  $pdf->Ln(5);
  $pdf->Cell(5, 2, '4b. Citizenship');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(25, 2, '');
  $pdf->Cell(7, 2, 'Male');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(10, 2, 'Filipino');
  $pdf->Cell(51.5, 2, '');
  $pdf->Cell(7, 2, 'Male');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(10, 2, 'Filipino');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '5. Residence');
  $pdf->Cell(25, 2, '');
  $pdf->SetFont('Arial', '', 7.5);
  $pdf->Cell(30, 2,'(House No., St., Barangay, City/Municipality, Province, Country)');
  $pdf->Cell(58, 2, '');
  $pdf->Cell(30, 2,'(House No., St., Barangay, City/Municipality, Province, Country)');
  $pdf->Ln(5);
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(5, 2, '');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(25, 2, 'Ubaliw, Polangui, Albay, Philippines');
  $pdf->Cell(63, 2, '');
  $pdf->Cell(25, 2, 'Ubaliw, Polangui, Albay, Philippines');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '6. Religion/');
  $pdf->Cell(25, 4, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(50, 4, 'Roman Catholic');
  $pdf->Cell(38, 4, '');
  $pdf->Cell(50, 4, 'Roman Catholic');
  $pdf->Ln(4);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '    Religious Sect');
  $pdf->Ln(8);
  $pdf->Cell(5, 4, '7. Civil Status');
  $pdf->Cell(25, 4, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(30, 4, 'Single');
  $pdf->Cell(58, 4, '');
  $pdf->Cell(30, 4, 'Single');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '8. Name of');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(First)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Middle)');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(Last)');
  $pdf->Cell(28, 2, '');
  $pdf->Cell(5, 2, '(First)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Middle)');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(Last)');
  $pdf->Ln(4);
  $pdf->Cell(5, 2, '    Father');
  $pdf->Cell(25, 2, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(5, 2, 'Dennis');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, 'Estrella');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, 'Echevarria');
  $pdf->Cell(28, 2, '');
  $pdf->Cell(5, 2, 'Dennis');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, 'Estrella');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, 'Echevarria');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 4, '9. Citizenship');
  $pdf->Cell(25, 4, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(40, 4, 'Filipino');
  $pdf->Cell(48, 4, '');
  $pdf->Cell(40, 4, 'Filipino');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '10. Maiden Name');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(First)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Middle)');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(Last)');
  $pdf->Cell(28, 2, '');
  $pdf->Cell(5, 2, '(First)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Middle)');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(Last)');
  $pdf->Ln(4);
  $pdf->Cell(5, 2, '  of Mother');
  $pdf->Cell(25, 2, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(5, 2, 'Ma. Gina');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, 'Florin');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, 'Sariba');
  $pdf->Cell(28, 2, '');
  $pdf->Cell(5, 2, 'Dennis');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, 'Estrella');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, 'Echevarria');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 4, '11. Citizenship');
  $pdf->Cell(25, 4, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(40, 4, 'Filipino');
  $pdf->Cell(48, 4, '');
  $pdf->Cell(40, 4, 'Filipino');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '12. Name of ');
  $pdf->Ln(4);
  $pdf->Cell(5, 2, '     Person/Wall');
  $pdf->Ln(4);
  $pdf->Cell(5, 2, '     Who Gave ');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(First)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Middle)');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(Last)');
  $pdf->Cell(28, 2, '');
  $pdf->Cell(5, 2, '(First)');
  $pdf->Cell(20, 2, '');
  $pdf->Cell(5, 2, '(Middle)');
  $pdf->Cell(25, 2, '');
  $pdf->Cell(5, 2, '(Last)');
  $pdf->Ln(4);
  $pdf->Cell(5, 2, '     Consent');
  $pdf->Cell(25, 2, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(5, 2, 'Not applicable');
  $pdf->Cell(5, 2, '');
  $pdf->Cell(5, 2, '');
  $pdf->Cell(73, 2, '');
  $pdf->Cell(5, 2, 'Not Applicable');
  $pdf->Cell(5, 2, '');
  $pdf->Cell(5, 2, '');
  $pdf->Ln(4);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '     or Advice');
  $pdf->Ln(8);
  $pdf->Cell(5, 4, '13. Relationship');
  $pdf->Cell(25, 4, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(40, 4, 'Not Applicable');
  $pdf->Cell(48, 4, '');
  $pdf->Cell(40, 4, 'Not applicable');
  $pdf->Ln(8);
  $pdf->SetFont('Arial', '', 9);
  $pdf->Cell(5, 2, '14. Residence');
  $pdf->Cell(25, 2, '');
  $pdf->SetFont('Arial', '', 7.5);
  $pdf->Cell(30, 2,'(House No., St., Barangay, City/Municipality, Province, Country)');
  $pdf->Cell(58, 2, '');
  $pdf->Cell(30, 2,'(House No., St., Barangay, City/Municipality, Province, Country)');
  $pdf->Ln(5);
  $pdf->Cell(5, 2, '');
  $pdf->Cell(25, 2, '');
  $pdf->SetFont('Arial', 'b', 9);
  $pdf->Cell(40, 2, 'Not Applicable');
  $pdf->Cell(48, 2, '');
  $pdf->Cell(40, 2, 'Not applicable');
  

  $pdf->Output();

?>